DROP TABLE IF EXISTS alerta CASCADE;
DROP TABLE IF EXISTS sesion CASCADE;
DROP TABLE IF EXISTS horario CASCADE;
DROP TABLE IF EXISTS lectura CASCADE;
DROP TABLE IF EXISTS sensor CASCADE;
DROP TYPE IF EXISTS estado_sesion CASCADE;
DROP TYPE IF EXISTS nivel_alerta CASCADE;
DROP TYPE IF EXISTS tipo_sensor CASCADE;